image: openjdk:11-jdk

stages:
  - build
  - test
  - build_image

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - docker info

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

build_image:
  script:
    - docker build -t my-docker-image .

after_script:
  - echo "End CI"